/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'washFold' : IDL.Null,
  'washIron' : IDL.Null,
  'dryCleaning' : IDL.Null,
  'expressLaundry' : IDL.Null,
  'blanketBedsheet' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'pickupDate' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'numClothes' : IDL.Nat,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAdminBookings' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(Booking))],
      ['query'],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Nat],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'washFold' : IDL.Null,
    'washIron' : IDL.Null,
    'dryCleaning' : IDL.Null,
    'expressLaundry' : IDL.Null,
    'blanketBedsheet' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'pickupDate' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'numClothes' : IDL.Nat,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAdminBookings' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(Booking))],
        ['query'],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Nat],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };