/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'serviceType' : ServiceType,
  'name' : string,
  'pickupDate' : string,
  'address' : string,
  'timestamp' : bigint,
  'numClothes' : bigint,
  'phone' : string,
}
export type ServiceType = { 'washFold' : null } |
  { 'washIron' : null } |
  { 'dryCleaning' : null } |
  { 'expressLaundry' : null } |
  { 'blanketBedsheet' : null };
export interface _SERVICE {
  'getAdminBookings' : ActorMethod<[string], [] | [Array<Booking>]>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'submitBooking' : ActorMethod<
    [string, string, string, string, ServiceType, bigint],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];